apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: github-labeler
  app.kubernetes.io/managed-by: antter
resources:
  - deploymentconfig.yaml
  - imagestream.yaml
  - route.yaml
  - service.yaml
